// src/components/BarSelect.vue
<template>
  <select
    :value="value"
    @input="$emit('input', $event.target.value)"
  >
    <option
      v-for="nBars in bars"
      :value="nBars"
      :key="nBars"
    >
      {{ nBars }}
    </option>
  </select>
</template>

<script>
export default {
  name: 'BarSelect',
  props: {
    bars: Array,
    value: Number,
  },
};
</script>

// app/components/BarSelect.jsx
import React from 'react';

export default function BarSelect(props) {
  return (
    <select
      value={props.value}
      onChange={event => props.onChange(event)}
    >
      {props.bars.map(nBars =>
        (
          <option value={nBars} key={nBars}>
            {nBars}
          </option>
        ),
      )}
    </select>
  );
}
