// src/components/PatternButton.vue
<template>
  <button
    :id=patternId
    :class="klazz"
    :value=pattern
    @click="$emit('click', pattern)"
    type="button"
  >
    <VexPattern :pattern="pattern" />
  </button>
</template>

<script>
import VexPattern from './VexPattern.vue';

export default {
  name: 'PatternButton',
  components: {
    VexPattern,
  },
  props: {
    active: Boolean,
    pattern: String,
  },
  computed: {
    patternId() {
      return this.pattern.replace(/ /g, '');
    },
    klazz() {
      const cls = this.active ? 'is-warning is-active' : '';
      return `${cls} button`;
    },
  },
};
</script>

<style scoped>
button > * {
  pointerEvents: 'none';
}
</style>

// app/components/PatternButton.jsx
import React from 'react';

import VexPattern from './VexPattern';

export default function PatternButton(props) {
  const patternId = props.pattern.replace(' ', '');
  const klazz = props.active ? 'pure-button-active' : '';

  return (
    <button
      id={patternId}
      type="button"
      className={klazz + ' pure-button'}
      value={props.pattern}
      onClick={(event, pattern) => props.onClick(event, pattern)}
    >
      <VexPattern pattern={props.pattern} />
    </button>
  );
}
