// src/components/ScoreControlForm.vue
<template>
  <form
    id="scoreControls"
    class="box"
  >
    <fieldset>
      <div class="field">
        <label
          class="label"
          htmlFor="timeSignature"
        >Time signature</label>
        <div class="field-body">
          <div class="field is-narrow">
            <div class="control">
              <div class="select is-fullwidth">
                <TimeSignatureSelect
                  v-model="timeSignature"
                  :initial-time-signature="initialTimeSignature"
                  :time-signatures="timeSignatures"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <label
          class="label"
          htmlFor="nBars"
        >Bars</label>
        <div class="field-body">
          <div class="field is-narrow">
            <div class="control">
              <div class="select is-fullwidth">
                <BarSelect
                  v-model.number="nBars"
                  :bars="bars"
                  :initial-n-bars="initialNBars"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <label class="label">Patterns</label>
        <div class="buttons are-large">
          <PatternButton
            v-for="buttonState in patternButtonStates"
            :key="buttonState.pattern"
            :active="buttonState.active"
            :pattern="buttonState.pattern"
            @click="onPatternClick"
          />
        </div>
      </div>

      <button
        type="button"
        class="button is-primary is-medium"
        @click="$emit('generate-score', nBars, checkedPatterns, timeSignature)"
      >
        Generate!
      </button>
    </fieldset>
  </form>
</template>

<script>
import BarSelect from './BarSelect.vue';
import PatternButton from './PatternButton.vue';
import TimeSignatureSelect from './TimeSignatureSelect.vue';

export default {
  name: 'ScoreControlForm',
  components: {
    BarSelect,
    PatternButton,
    TimeSignatureSelect,
  },
  props: {
    bars: Array,
    initialNBars: Number,
    initialCheckedPatterns: Array,
    patterns: Array,
    initialTimeSignature: String,
    timeSignatures: Array,
  },
  data() {
    return {
      checkedPatterns: this.initialCheckedPatterns,
      nBars: this.initialNBars,
      timeSignature: this.initialTimeSignature,
    };
  },
  computed: {
    patternButtonStates() {
      return this.patterns.map(
        (p) => (
          {
            pattern: p,
            active: this.checkedPatterns.includes(p),
          }
        ),
      );
    },
  },
  methods: {
    onPatternClick(pattern) {
      if (this.checkedPatterns.includes(pattern)) {
        this.checkedPatterns = this.checkedPatterns.filter((item) => item !== pattern);
      } else {
        this.checkedPatterns.push(pattern);
      }
    },
  },
};
</script>

// app/components/ScoreControlForm.jsx
import React from 'react';
import PropTypes from 'prop-types';

import BarSelect from './BarSelect';
import PatternButton from './PatternButton';
import TimeSignatureSelect from './TimeSignatureSelect';


/**
 * VexFlow score generation settings
 */
export default class ScoreControlForm extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      nBars: props.defaultBars,
      checkedPatterns: props.checkedPatterns,
      timeSignature: props.defaultTimeSignature,
    };
  }

  handleChangeTimeSignature(event) {
    this.setState({ timeSignature: event.target.value });
  }

  handleChangeBar(event) {
    this.setState({ nBars: event.target.value });
  }

  handleChangePattern(event) {
    const { checkedPatterns } = this.state;
    const pattern = event.target.value;

    if (checkedPatterns.has(pattern)) {
      checkedPatterns.delete(pattern);
    } else {
      checkedPatterns.add(pattern);
    }

    this.setState(checkedPatterns);
  }

  handleClick(event) {
    this.props.onClick(event, this.state);
  }

  render() {
    return (
      <form className="box" id="scoreControls">
        <fieldset>
          <div className="field">
            <label className="label" htmlFor="timeSignature">Time signature</label>
            <div className="field-body">
              <div class="field is-narrow">
                <div class="control">
                  <div class="select is-fullwidth">
                    <TimeSignatureSelect
                      signatures={this.props.signatures}
                      value={this.state.timeSignature}
                      onChange={event => this.handleChangeTimeSignature(event)}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="field">
            <label className="label" htmlFor="nBars">Bars</label>
            <div className="field-body">
              <div class="field is-narrow">
                <div class="control">
                  <div class="select is-fullwidth">
                    <BarSelect
                      bars={this.props.bars}
                      value={this.state.nBars}
                      onChange={event => this.handleChangeBar(event)}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="field">
            <label className="label">Patterns</label>
            <div className="buttons are-large">
          {this.props.patterns.map(
            pattern => (
              <PatternButton
                key={pattern}
                pattern={pattern}
                active={this.state.checkedPatterns.has(pattern)}
                onClick={event => this.handleChangePattern(event)}
              />
            ),
          )}
            </div>
          </div>

          <button
            type="button"
            className="button is-primary is-medium"
            onClick={event => this.handleClick(event)}
          >
            Generate!
          </button>
        </fieldset>
      </form>
    );
  }
}

ScoreControlForm.propTypes = {
  defaultBars: PropTypes.number.isRequired,
  checkedPatterns: PropTypes.instanceOf(Set).isRequired,
  defaultTimeSignature: PropTypes.string.isRequired,
  bars: PropTypes.arrayOf(PropTypes.number).isRequired,
  patterns: PropTypes.arrayOf(PropTypes.string).isRequired,
  signatures: PropTypes.arrayOf(PropTypes.string).isRequired,
  onClick: PropTypes.func.isRequired,
};
