// src/components/VexScore.vue
<template>
  <div id="score"/>
</template>

<script>
import generateSvgScore from '../VexUtils';

export default {
  name: 'VexScore',
  props: {
    nBars: Number,
    patterns: Array,
    timeSignature: String,
  },
  mounted() {
    this.render();
  },
  updated() {
    this.render();
  },
  methods: {
    render() {
      const scoreDiv = document.getElementById('score');
      scoreDiv.innerHTML = '';
      scoreDiv.appendChild(generateSvgScore(this.nBars, this.patterns, this.timeSignature));
    },
  },
};
</script>

// app/components/VexScore.jsx
import React from 'react';

import generateSvgScore from '../VexUtils';


export default class Score extends React.Component {
  constructor(props) {
    super(props);
    this.scoreRef = null;
  }

  componentDidMount() {
    this.scoreRef.appendChild(generateSvgScore(
      this.props.nBars,
      this.props.patterns,
      this.props.timeSignature,
    ));
  }
  componentWillReceiveProps(newProps) {
    this.props = newProps;
    this.scoreRef.innerHTML = '';
    this.scoreRef.appendChild(generateSvgScore(
      this.props.nBars,
      this.props.patterns,
      this.props.timeSignature,
    ));
  }

  render() {
    return <div ref={(el) => { this.scoreRef = el; }} />;
  }
}
