// app/components/TimeSignatureSelect.jsx
import React from 'react';

export default function TimeSignatureSelect(props) {
  return (
    <select
      value={props.value}
      onChange={event => props.onChange(event)}
    >
      {props.signatures.map(
        signature => (
          <option value={signature} key={signature}>
            {signature}
          </option>
        ),
      )}
    </select>
  );
}

// src/components/TimeSignatureSelect.vue
<template>
  <select
    :value="value"
    @input="$emit('input', $event.target.value)"
  >
    <option
      v-for="timeSignature in timeSignatures"
      :value="timeSignature"
      :key="timeSignature"
    >
      {{ timeSignature }}
    </option>
  </select>
</template>

<script>
export default {
  name: 'TimeSignatureSelect',
  props: {
    timeSignatures: Array,
    value: String,
  },
};
</script>
